site_name: Splashtop Syslog Guide

theme:
  name: material
  language: en
  logo: assets/Logo.png
  favicon: assets/shuidi.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.instant
    - navigation.expand
    - content.code.annotate

nav:
  - Syslog:
      - Overview: syslog-events.md
      - Syslog Format: events/syslog-format.md
      - Events and Fields:
          - Auth: events/Auth.md
          - Management: events/Management.md
          - Log: events/Log.md
          - Else: events/Syslog events and fields.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
plugins:
  - search
