site_name: Splashtop Syslog Guide

theme:
  name: material
  language: en
  logo: assets/Logo.png
  favicon: assets/shuidi.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.instant
    - navigation.expand
    - content.code.annotate

nav:
  - Overview: index.md
  - Events and Fields:
      - Auth: category/auth.md
      - Session: category/session.md
      - Log: category/log.md
      - Endpoint: category/endpoint.md
      - Management: category/management.md
      - Service Desk: category/service_desk.md
      - Settings: category/settings.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
plugins:
  - search
extra_css:
  - assets/css/extra.css
